# Generated by Django 6.0.4 on 2026-04-16 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('All in Mauritius', 'All in Mauritius'), ('Flic En Flac', 'Flic En Flac'), ('GrandBaie', 'GrandBaie'), ('Tamarin', 'Tamarin')], max_length=32)),
                ('side', models.CharField(choices=[('West', 'West'), ('North', 'North'), ('East', 'East'), ('South', 'South'), ('Center', 'Center')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('order_number', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property_type', models.CharField(choices=[('Appartment', 'Appartment'), ('Villa', 'Villa')], max_length=20)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('ac', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('hot_water', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('roof_access', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='listings.property')),
            ],
            options={
                'ordering': ['sort_order', 'month_year'],
            },
        ),
    ]
