# Generated by Django 6.0.4 on 2026-04-16 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='properties/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='property',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='properties/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='property',
            name='video_3',
            field=models.FileField(blank=True, null=True, upload_to='properties/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
    ]
