# Generated by Django 6.0.4 on 2026-04-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_image_1_property_image_10_property_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='property_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='property_languages',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=255),
        ),
        migrations.DeleteModel(
            name='PropertyAvailability',
        ),
    ]
