# Generated by Django 6.0.4 on 2026-04-17 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_availability_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='availability_datetime',
        ),
        migrations.AddField(
            model_name='property',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='max_stay',
            field=models.PositiveIntegerField(default=30, help_text='Maximum nights stay', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='property',
            name='min_stay',
            field=models.PositiveIntegerField(default=1, help_text='Minimum nights stay', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
