# Generated by Django 6.0.4 on 2026-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_property_availability_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='video_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_3',
        ),
        migrations.AddField(
            model_name='property',
            name='bbq_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='tv',
            field=models.BooleanField(default=False),
        ),
    ]
