# Generated by Django 6.0.4 on 2026-04-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_property_video_2_remove_property_video_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_languages',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_9',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_1',
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/bedroom/'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/building/'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/land/'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/living_room/'),
        ),
        migrations.AddField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/main/'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='vc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/vc/'),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
