# Generated by Django 6.0.4 on 2026-04-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_property_address_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='checkout_date',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Flic En Flac', 'Flic En Flac'), ('GrandBaie', 'GrandBaie'), ('Tamarin', 'Tamarin')], max_length=32),
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='listings.property')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.property')),
            ],
            options={
                'ordering': ['check_in'],
                'indexes': [models.Index(fields=['property', 'check_in', 'check_out'], name='listings_bo_propert_fd3274_idx')],
            },
        ),
    ]
