# Generated by Django 6.0.4 on 2026-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_property_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owners/photos/'),
        ),
    ]
