# Generated by Django 6.0.4 on 2026-04-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_property_owner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('GrandBaie', 'Grand Baie'), ('Cap Malheureux', 'Cap Malheureux'), ('Pereybere', 'Pereybere'), ('Trou aux Biches', 'Trou aux Biches'), ('Mont Choisy', 'Mont Choisy'), ('Pointe aux Piments', 'Pointe aux Piments'), ('Goodlands', 'Goodlands'), ('Calodyne', 'Calodyne'), ('Flic En Flac', 'Flic En Flac'), ('Tamarin', 'Tamarin'), ('Black River', 'Black River (Rivière Noire)'), ('La Gaulette', 'La Gaulette'), ('Le Morne', 'Le Morne'), ('Wolmar', 'Wolmar'), ('Cascavelle', 'Cascavelle'), ('Belle Mare', 'Belle Mare'), ("Trou d'Eau Douce", "Trou d'Eau Douce"), ('Palmar', 'Palmar'), ('Flacq', 'Centre de Flacq'), ('Poste Lafayette', 'Poste Lafayette'), ('Quatre Cocos', 'Quatre Cocos'), ('Blue Bay', 'Blue Bay'), ('Mahebourg', 'Mahébourg'), ('Bel Ombre', 'Bel Ombre'), ('Souillac', 'Souillac'), ('Riambel', 'Riambel'), ("Pointe d'Esny", "Pointe d'Esny"), ('Curepipe', 'Curepipe'), ('Quatre Bornes', 'Quatre Bornes'), ('Vacoas', 'Vacoas-Phoenix'), ('Phoenix', 'Phoenix'), ('Beau Bassin', 'Beau Bassin-Rose Hill'), ('Rose Hill', 'Rose Hill'), ('Moka', 'Moka'), ('Reduit', 'Réduit'), ('Port Louis', 'Port Louis (Capital)'), ('Pamplemousses', 'Pamplemousses'), ('Plaine Magnien', 'Plaine Magnien (Airport area)'), ('Quartier Militaire', 'Quartier Militaire'), ('Saint Pierre', 'Saint Pierre')], max_length=32),
        ),
    ]
